<?php
/**
 * Created by PhpStorm.
 * User: wap19
 * Date: 05/02/15
 * Time: 14:02
 */
?>

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="description" content="Bienvenue sur mon site de test">
    <link rel="stylesheet" href="css/font-awesome.min.css"/>
    <link rel="stylesheet" href="css/normalize.css"/>
    <link rel="stylesheet" href="css/menu.css"/>
    <link rel="stylesheet" href="css/style.css"/>
    <title></title>
</head>

<body>
<nav class="menu">
    <ul>
        <li><a href="list.php">List</a></li>
        <li><a href="add.php">Add</a></li>
        <li><a href="remove.php">Remove</a></li>
    </ul>
</nav>
