<?php
/**
 * Created by PhpStorm.
 * User: wap19
 * Date: 05/02/15
 * Time: 13:50
 */
?>

<?php require_once "head.phtml"; ?>

<div class="container">
    <h1>Add a task</h1>

    <?php if(!empty($message))
    {
        echo "<div class='message_error'>".$message."</div>";
    }?>

    <form method="post" action="">
        <div><label for="title">Title</label><input type="text" id="title" name="title"></div>
        <div><label for="description">Description</label><textarea rows="4" id="description" name="description"></textarea>
        </div>
        <div><label for="date">Date</label><input type="date" id="date" name="date"></div>
        <div><label for="priority">Priority</label><select id="priority" name="priority">
                <option selected="selected">Critical</option>
                <option>High</option>
                <option>Medium</option>
                <option>Trivial</option>
            </select></div>
        <div>
            <input type="submit" value="submit" name="submit">
        </div>
    </form>
</div>

<?php require_once "footer.phtml"; ?>
