<!--/**
 * Created by PhpStorm.
 * User: wap19
 * Date: 30/01/15
 * Time: 11:37
 */-->

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <h1><?= $titre; ?></h1>

        <form action="" name="" method="post">
            <input type="text" name="number"/>
            <input type="submit"/>
        </form>

    <?= $message; ?>

</body>
</html>