<div id="message">
    <p>
        <?php if(array_key_exists("message", $_SESSION)) : ?>
            <?= $_SESSION["message"]; ?>
            <?php unset($_SESSION["message"]); ?>
        <?php endif; ?>
    </p>
    <p>
        <?php if(array_key_exists("error", $_SESSION)) : ?>
            <?= $_SESSION["error"]; ?>
            <?php unset($_SESSION["error"]); ?>
        <?php endif; ?>
    </p>
</div>

<h5>Bonjour, qui êtes vous?</h5>


<form action="login.php" method="post">
    <label for="login"> Votre nom</label>
    <input type="text" name="login" id="login">
    <label for="password"> Mot de passe </label>
    <input type="password" name="password" id="password">
    <input type="submit" value="Login"/>

</form>

<h5>Pas encore inscrit ? </h5>

<form action="addUser.php" method="post">
    <label for="name">Nom</label>
    <input type="text" name="name" id="name"/>
    <label for="mdp">Mot de passe</label>
    <input type="password" name="mdp" id="mdp"/>
    <input type="submit" value="Enregistrer"/>
</form>






