<div class="row">
    <div class="col-lg-8">
        <?php foreach($articlesDisplay as $value) : ?>
            <div class="blogpost clearfix">
                <div class="panel panel-default">
                    <div class="panel-body narrow">
                        <h2><?= $value['title']; ?></h2>
                        <hr>
                        <p class="post-header">
                            <a id="<?= $value["id"]; ?>" class="readMore">
                                <span class="pull-right"><span class="glyphicon glyphicon-comment"></span> Comment [<?= sizeof($value["commentary"]); ?>]</span>
                            </a>
                            <a class="<?=$value["id"]; ?>" id="delete" href="deletepost.php?id=<?=$value["id"]; ?>">
                                Delete
                            </a>
                            <a id="<?=$value["id"]; ?>" class="update">
                                Update
                            </a>
                            <span class="glyphicon glyphicon-user"></span>
                            <?= $value['username']; ?>
                            <span class="glyphicon glyphicon-time"></span>
                            <?= date($value['date_article']); ?>
                            <br>
                        </p>
                        <p>
                            <?php foreach($value["tags"] as $valueTags) : ?>
                            <a href=""><span class="btn btn-default btn-xs">
                                    <span class="glyphicon glyphicon-tag">

                                    </span><?= $valueTags["content_tag"]; ?></span>
                            </a>
                            <?php endforeach; ?>
                        </p>
                        <hr>
                        <div class="flexslider">
                            <ul class="slides">
                                <?php foreach($value["image"] as $valueImg) : ?>
                                    <li>
                                        <img src="<?= $valueImg["url"]; ?>" draggable="false">
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                        <p><?= $value['content_article']; ?></p>
                        <a id="<?= $value["id"]; ?>" class="pull-right readmore readMore"><button class="btn btn-default" type="button">Read More</button></a>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>

    <div class="col-md-4">
        <div class="well">
            <?php if(array_key_exists("id", $_SESSION)) : ?>
                <p>Hello <?= $_SESSION["username"]; ?></p>
                <ul class="list-unstyled">
                    <li><a href="logout.php">Logout</a></li>
                    <li><a href="createpost.php">Create post</a></li>
                </ul>
            <?php else : ?>
                <p>Hello there stranger! ◕ ◡ ◕ </p>
                <ul class="list-unstyled">
                    <li><a href="login.php">Login</a></li>
                </ul>
            <?php endif; ?>
        </div>
    </div>
</div>


<div id="edit-basic-information">
    <div id="edit-basic-information-container">

    </div>
</div>

<div id="edit-basic-information2">
    <div id="edit-basic-information-container2">

    </div>
</div>

