<h2>Connectez vous !</h2>
<p class="success"></p>
<p class="alert"></p>
<form action="" method="post" id="verifUser">
    <div class="form-group" id="loginGroup">
        <label for="login">Login</label>
        <input name="login" type="text" class="form-control" id="login" placeholder=" Enter you're name...">
    </div>
    <div class="form-group" id="pwdGroup">
        <label for="pwd">Password</label>
        <input name="pwd" type="password" class="form-control" id="pwd">
    </div>

    <button type="submit" class="btn btn-default">Submit</button>
</form>

<div class="center">
    Pas encore de compte ? <a href="register.php">Inscrivez-vous !</a>
</div>