<h2>Inscrivez vous !</h2>
<form action="" method="post" id="addUser">
    <div class="form-group" id="nameGroup">
        <label for="name">Name</label>
        <input type="text" name="name" class="form-control" id="name">
    </div>
    <div class="form-group" id="emailGroup">
        <label for="email">Email address</label>
        <input type="email" name="email" class="form-control" id="email">
    </div>
    <div class="form-group" id="pwdGroup">
        <label for="pwd">Password</label>
        <input type="password" class="form-control" id="pwd">
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>

<div id="divQueryResult">
    <h2 id="queryResult"></h2>
</div>